// Copyright 2026 Casey West
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package okf

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// neighborhood returns the top-level directory of a bundle-relative slash path,
// or "" for a root-level node (rendered under a "(root)" group).
func neighborhood(rel string) string {
	if i := strings.IndexByte(rel, '/'); i >= 0 {
		return rel[:i]
	}
	return ""
}

// nodeTitle returns the node's title frontmatter, falling back to the file's
// base name (without .md) when absent.
func nodeTitle(n *Node) string {
	if t, ok := n.Frontmatter["title"].(string); ok && strings.TrimSpace(t) != "" {
		return t
	}
	return strings.TrimSuffix(path.Base(n.Path), ".md")
}

// RenderIndex produces a deterministic, neighborhood-grouped index.md body for
// the bundle: Index frontmatter, then one section per top-level neighborhood
// (sorted), each listing its concept nodes (sorted by path) as titled markdown
// links annotated with the node's type. Reserved files are excluded. The output
// is byte-stable across runs (all ordering is via sort), and passes Validate.
func RenderIndex(b *Bundle) string {
	groups := map[string][]string{}
	for p := range b.Nodes {
		nb := neighborhood(p)
		groups[nb] = append(groups[nb], p)
	}
	names := make([]string, 0, len(groups))
	for nb := range groups {
		names = append(names, nb)
	}
	sort.Strings(names)

	var sb strings.Builder
	sb.WriteString("---\ntype: Index\n---\n\n# Knowledge Base\n\n")
	sb.WriteString("_Generated by `okfctl index build`. Do not edit by hand; run `okfctl index build` to regenerate._\n")
	if len(names) == 0 {
		sb.WriteString("\n_No nodes yet._\n")
		return sb.String()
	}
	for _, nb := range names {
		heading := nb
		if heading == "" {
			heading = "(root)"
		}
		sb.WriteString("\n## " + heading + "\n\n")
		paths := groups[nb]
		sort.Strings(paths)
		for _, p := range paths {
			n := b.Nodes[p]
			sb.WriteString(fmt.Sprintf("- [%s](%s) — %s\n", nodeTitle(n), p, n.Type()))
		}
	}
	return sb.String()
}

// IndexInSync reports whether the on-disk index.md matches what RenderIndex would
// generate for the current bundle. When stale, it returns a short human-readable
// report. A missing index.md counts as out of sync.
func IndexInSync(b *Bundle) (bool, string) {
	want := RenderIndex(b)
	onDisk, err := os.ReadFile(filepath.Join(b.Root, "index.md"))
	if err != nil {
		return false, "index.md is missing or unreadable; run `okfctl index build`"
	}
	if string(onDisk) == want {
		return true, ""
	}
	return false, "index.md is out of date; run `okfctl index build` to regenerate"
}

// AppendLog prepends a timestamped entry to log.md (newest-first), creating the
// file with a heading when absent. A multi-line message is flattened to its first
// line to keep the log well-formed; an empty message is rejected.
func AppendLog(root, message string) error {
	message = strings.TrimSpace(message)
	if i := strings.IndexByte(message, '\n'); i >= 0 {
		message = message[:i]
	}
	if message == "" {
		return fmt.Errorf("log message must not be empty")
	}
	entry := fmt.Sprintf("- %s — %s\n", time.Now().UTC().Format("2006-01-02"), message)

	p := filepath.Join(root, "log.md")
	existing, err := os.ReadFile(p)
	if err != nil {
		return os.WriteFile(p, []byte(logHeader+entry), 0o644)
	}
	// Strip the header, then drop the scaffold placeholder when it is the only
	// content — otherwise the fresh-scaffold "no entries yet" hint stays pinned
	// below every real entry.
	rest := strings.TrimPrefix(string(existing), logHeader)
	rest = strings.TrimPrefix(rest, logPlaceholder)
	return os.WriteFile(p, []byte(logHeader+entry+rest), 0o644)
}

// ReadLog returns the log.md body (empty string if the file is absent).
func ReadLog(root string) (string, error) {
	data, err := os.ReadFile(filepath.Join(root, "log.md"))
	if os.IsNotExist(err) {
		return "", nil
	}
	if err != nil {
		return "", err
	}
	return string(data), nil
}
