// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package okf

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// OKF §8: "Index files contain no frontmatter." OKF §12: the bundle-root
// index.md may carry a frontmatter block containing okf_version — "the only
// place frontmatter is permitted in an index.md" — and nothing else. These
// tests pin `index build` output to that grammar so the tool that enforces the
// spec cannot itself emit non-conformant indexes.

// frontmatterBlock returns the raw frontmatter body (between the leading and
// closing `---` fences) when the rendered index opens with one, and ("", false)
// when the index has no frontmatter at all.
func frontmatterBlock(rendered string) (string, bool) {
	if !strings.HasPrefix(rendered, "---\n") {
		return "", false
	}
	rest := rendered[len("---\n"):]
	end := strings.Index(rest, "\n---\n")
	if end < 0 {
		return "", false
	}
	return rest[:end], true
}

func TestRenderIndex_NoFrontmatterWithoutOkfVersion(t *testing.T) {
	dir := t.TempDir()
	// A bundle with concept nodes but NO okf_version marker (no on-disk
	// index okf_version, no .okf sidecar) must render with zero frontmatter.
	if err := os.WriteFile(filepath.Join(dir, "log.md"), []byte(logHeader+logPlaceholder), 0o644); err != nil {
		t.Fatal(err)
	}
	writeNode(t, dir, "wine/tannin.md", "Reference", "Tannin")

	b, err := Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := RenderIndex(b)

	if _, has := frontmatterBlock(got); has {
		t.Errorf("index without an okf_version marker must have NO frontmatter; got:\n%s", got)
	}
	if strings.Contains(got, "type: Index") {
		t.Errorf("index must never emit `type: Index` frontmatter; got:\n%s", got)
	}
}

func TestRenderIndex_RootFrontmatterHasOnlyOkfVersion(t *testing.T) {
	dir := t.TempDir()
	// A .okf sidecar pins the bundle's okf_version, and the bundle-root index
	// carries it — the sole sanctioned frontmatter key (§12).
	if err := os.WriteFile(filepath.Join(dir, ".okf"), []byte("okf_version: 0.1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "index.md"), []byte("---\nokf_version: \"0.1\"\n---\n\n# Knowledge Base\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "log.md"), []byte(logHeader+logPlaceholder), 0o644); err != nil {
		t.Fatal(err)
	}
	writeNode(t, dir, "wine/tannin.md", "Reference", "Tannin")

	b, err := Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := RenderIndex(b)

	fm, has := frontmatterBlock(got)
	if !has {
		t.Fatalf("root index with an okf_version marker must carry a frontmatter block; got:\n%s", got)
	}
	// The block must contain exactly one key line, and it must be okf_version.
	var keys []string
	for _, line := range strings.Split(strings.TrimSpace(fm), "\n") {
		if line = strings.TrimSpace(line); line != "" {
			keys = append(keys, line)
		}
	}
	if len(keys) != 1 || !strings.HasPrefix(keys[0], "okf_version:") {
		t.Errorf("root frontmatter must contain exactly the okf_version key; got keys %q in:\n%s", keys, got)
	}
	if strings.Contains(fm, "type:") {
		t.Errorf("root frontmatter must not carry `type:`; got:\n%s", got)
	}
	if !strings.Contains(fm, `okf_version: "0.1"`) {
		t.Errorf("root frontmatter must preserve the okf_version value; got:\n%s", got)
	}
}

func TestRenderIndex_NoGeneratedByBoilerplate(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "log.md"), []byte(logHeader+logPlaceholder), 0o644); err != nil {
		t.Fatal(err)
	}
	writeNode(t, dir, "wine/tannin.md", "Reference", "Tannin")

	b, err := Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	got := RenderIndex(b)

	if strings.Contains(got, "Generated by") {
		t.Errorf("index body must not carry the `Generated by` boilerplate line; got:\n%s", got)
	}
}

func TestScaffold_IndexHasNoFrontmatter(t *testing.T) {
	dir := t.TempDir()
	if err := Scaffold(dir); err != nil {
		t.Fatalf("Scaffold: %v", err)
	}
	raw, err := os.ReadFile(filepath.Join(dir, "index.md"))
	if err != nil {
		t.Fatal(err)
	}
	if _, has := frontmatterBlock(string(raw)); has {
		t.Errorf("scaffolded index.md must have NO frontmatter; got:\n%s", raw)
	}
	if strings.Contains(string(raw), "type: Index") {
		t.Errorf("scaffolded index.md must not seed `type: Index`; got:\n%s", raw)
	}
}
