// Copyright 2026 Casey West
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package okf

import (
	"fmt"
	"path"
	"sort"
	"strings"
)

// neighborhood returns the top-level directory of a bundle-relative slash path,
// or "" for a root-level node (rendered under a "(root)" group).
func neighborhood(rel string) string {
	if i := strings.IndexByte(rel, '/'); i >= 0 {
		return rel[:i]
	}
	return ""
}

// nodeTitle returns the node's title frontmatter, falling back to the file's
// base name (without .md) when absent.
func nodeTitle(n *Node) string {
	if t, ok := n.Frontmatter["title"].(string); ok && strings.TrimSpace(t) != "" {
		return t
	}
	return strings.TrimSuffix(path.Base(n.Path), ".md")
}

// RenderIndex produces a deterministic, neighborhood-grouped index.md body for
// the bundle: Index frontmatter, then one section per top-level neighborhood
// (sorted), each listing its concept nodes (sorted by path) as titled markdown
// links annotated with the node's type. Reserved files are excluded. The output
// is byte-stable across runs (all ordering is via sort), and passes Validate.
func RenderIndex(b *Bundle) string {
	groups := map[string][]string{}
	for p := range b.Nodes {
		nb := neighborhood(p)
		groups[nb] = append(groups[nb], p)
	}
	names := make([]string, 0, len(groups))
	for nb := range groups {
		names = append(names, nb)
	}
	sort.Strings(names)

	var sb strings.Builder
	sb.WriteString("---\ntype: Index\n---\n\n# Knowledge Base\n\n")
	sb.WriteString("_Generated by `okfctl index build`. Do not edit by hand; run `okfctl index build` to regenerate._\n")
	if len(names) == 0 {
		sb.WriteString("\n_No nodes yet._\n")
		return sb.String()
	}
	for _, nb := range names {
		heading := nb
		if heading == "" {
			heading = "(root)"
		}
		sb.WriteString("\n## " + heading + "\n\n")
		paths := groups[nb]
		sort.Strings(paths)
		for _, p := range paths {
			n := b.Nodes[p]
			sb.WriteString(fmt.Sprintf("- [%s](%s) — %s\n", nodeTitle(n), p, n.Type()))
		}
	}
	return sb.String()
}
